# Generated by Django 5.0.4 on 2024-04-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_product', models.BooleanField(default=False)),
                ('product_name', models.CharField(max_length=100)),
                ('cate_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('calories', models.IntegerField()),
                ('sugars', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('caffeine', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('sodium', models.IntegerField()),
            ],
        ),
    ]
